# (APPENDIX) Appendix {-}

# About assignments and RMarkdown {#rmarkdown}

There are some important things to consider when handing in the assignments:

1. All answers, plots and code should be contained in _a single document_. This needs to be either a word or a pdf document.
2. The document should contain **all the code** you used to complete the assignment. It should also contain **all relevant output** from the code. This should be in a font that's suitable for programming (i.e., where all characters have the same width), for example Source code pro.
3. You are allowed to work together, but **identical hand-ins are not allowed**. Similarly, all the text should be your own, **copying from the book, tutorials or any other sources is not allowed**. If you really want to quote someone, you should make it clear that it's a quote, and cite it properly. It is OK to use the *code* in the tutorials without citing that.

One simple way of combining code, plots and text is to write in a word document where you also paste your code and figures that you've exported from R. Another way is to use RMarkdown, which will be introduced in the next section.

### RMarkdown {-}

Rmarkdown ...