# Week 9 assignment {- #w09}

#### 1. Working with trees {-}

a) Draw a random tree with 23 taxa. Make it a radial (or "fan") tree, with an edge width of 1.5. It must be any colour other than black. _Tip: for naming the tree tips, check out the_ `letters` _object that is built into R_

b) Extract the Proaves clade from the bird.orders dataset and plot it. Then, test whether ducks and geese (Anseriformes) and chickens and turkeys (Galliformes) are monophyletic. _Hint: Find out which node that represents the last common ancestor of the Proaves._

#### 2. Primates {-}

In the tutorial, we worked with a subset (`hominidae`) of the `primates` data set. In this part of the assignment you will do the same analyses with the full data set.

a) Using the full primates dataset, calculate the pairwise distance matrix using the most suitable sequence model. Then, construct both UPGMA and NJ trees and plot them.

b) Root the NJ tree with Mouse as an outgroup. What is the parsimony of the rooted NJ tree and the UPGMA tree, and which is most parsimonous?

c) Look at the placement of Bovine in the rooted NJ tree. Is it what you would expect? What can explain this placement?

#### 3. Village dogs PCA {-}

a) From the eigenvalues generated by our `dogs_pca` (i.e. the subset we worked with in the tutorial), how many principal components should we consider to account for approximately 10% of the variance?

For the rest of the assignment, we will be working with the PCA results and eigenvalues from the full village dogs data set. The PCA can be found [here](https://bios1140.github.io/data/full_village_dogs_pca.tsv). The eigenvalues can be found [here](https://bios1140.github.io/data/full_village.eigenval).

b) Plot the PCA for the full village dogs data set, colouring the points by location.

c) Which group is the most divergent? What other patterns can you see in the PCA?

To read in the eigenvalues, try using the `scan()` function. If you open the file, you can see that it's just a plain text file with a single column of values, so `read.table()` could also work.

d) What proportion of the variance do the first two principal components explain?
